name: covidwatch
description: Watching COVID19
version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # icons
  feather_icons_flutter: ^4.7.4
  # rest
  http: ^0.12.0+4
  async: ^2.4.0
  # storage
  sembast: ^1.15.1
  shared_preferences: ^0.5.6
  path_provider: ^0.5.0+1
  # bloc
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  meta: ^1.1.6
  # logger
  logger: ^0.7.0
  # others
  timeago: ^2.0.26
  url_launcher: ^5.4.2
  flutter_svg: ^0.17.0
  enum_to_string: ^1.0.9
  fluttertoast: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  fonts:
    - family: Arimo
      fonts:
        - asset: fonts/Arimo-Regular.ttf
        - asset: fonts/Arimo-Bold.ttf
          weight: 700
  assets:
    - flags/
